### ISSUE TITLE
# Bud, I literally code free projects. I know the ins and outs of API requests. I know how to make a newer, more modern, and more better version of what BS this project is. But I am choosing not to because I am not going to waste my energy because of some developer who cant even spend his energy, 4 hours of his life at most, to code an update. No way that is happening. I already have a barebones patch to the new update, but it's private for a reason. I'm protesting against lazy development like this,  # Also @wearrrrr I don't care. I have a right to be mad about lazy development teams like this. Imagine if ur favorite game company decided to never update it again and it kept saying "If you want updates so bad make them yourself and make a pull request" Cuz thats how ur looking like right now.

### ISSUE THREAD

**Issue by meghan06** [smorenitez/Fuck-DoorDash#1]
# Bud, I literally code free projects. I know the ins and outs of API requests. I know how to make a newer, more modern, and more better version of what BS this project is. But I am choosing not to because I am not going to waste my energy because of some developer who cant even spend his energy, 4 hours of his life at most, to code an update. No way that is happening. I already have a barebones patch to the new update, but it's private for a reason. I'm protesting against lazy development like this,

# Also @wearrrrr I don't care. I have a right to be mad about lazy development teams like this. Imagine if ur favorite game company decided to never update it again and it kept saying "If you want updates so bad make them yourself and make a pull request" Cuz thats how ur looking like right now.

**Comment by IAGOnGithub** [comment]
Bump.
